name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Установка зависимостей
        run: npm ci

      - name: Проверка линтером
        run: npm run lint

      - name: Сборка проекта
        run: npm run build

      - name: Добавление bundlesize в package.json
        run: |
          # Добавляем bundlesize в package.json
          npm install --save-dev bundlesize
          # Используем jq для модификации package.json
          jq '.bundlesize = [{"path": "./dist/**/*.js", "maxSize": "100 kB"}, {"path": "./dist/**/*.css", "maxSize": "20 kB"}]' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Анализ размера бандла
        run: npx bundlesize

      - name: Установка и настройка Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.11.x
          cat > lighthouserc.cjs << 'EOL'
          module.exports = {
            ci: {
              collect: {
                staticDistDir: "./dist",
                numberOfRuns: 1,
              },
              upload: {
                target: "temporary-public-storage",
              },
              assert: {
                preset: "lighthouse:recommended",
              },
            },
          };
          EOL

      - name: Запуск Lighthouse CI
        run: lhci autorun || true

      - name: Проверка безопасности зависимостей
        run: npm audit || true

      # Сохраняем артефакты сборки для использования в job deploy
      - name: Сохранение артефактов сборки
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

  # Новый job для деплоя на Netlify
  deploy:
    # Запускаем только при push в main, не для pull request
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build # Ждем завершения job build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Загружаем артефакты сборки из предыдущего job
      - name: Загрузка артефактов сборки
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      # Деплой на Netlify
      - name: Деплой на Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
