name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Установка зависимостей
        run: npm ci

      - name: Проверка линтером
        run: npm run lint

      - name: Запуск тестов с покрытием
        run: npm test -- --coverage

      - name: Сохранение отчета о покрытии
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      - name: Сборка проекта
        run: npm run build

      - name: Анализ размера бандла
        run: npx bundlesize

      - name: Запуск Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.11.x
          lhci autorun

      - name: Запуск SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Проверка безопасности зависимостей
        run: npm audit
