name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Установка зависимостей
        run: npm ci

      - name: Проверка линтером
        run: npm run lint

      - name: Сборка проекта
        run: npm run build

      - name: Добавление bundlesize в package.json
        run: |
          # Добавляем bundlesize в package.json
          npm install --save-dev bundlesize
          # Используем jq для модификации package.json
          jq '.bundlesize = [{"path": "./dist/**/*.js", "maxSize": "100 kB"}, {"path": "./dist/**/*.css", "maxSize": "20 kB"}]' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Анализ размера бандла
        run: npx bundlesize

      - name: Установка и настройка Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.11.x
          echo 'module.exports = {ci: {collect: {url: ["http://localhost:3000"], startServerCommand: "npm run preview", numberOfRuns: 1}, upload: {target: "temporary-public-storage"}}}' > lighthouserc.js

      - name: Запуск Lighthouse CI
        run: lhci autorun || true

      - name: Проверка безопасности зависимостей
        run: npm audit || true
